### ISSUE TITLE
VS2015 shortcut page still mentions 2013 in title

### ISSUE THREAD

**Issue by ctolkien** [madskristensen/ShortcutExporter#6]

**Comment by jchannon** [comment]
Just seen that too http://visualstudioshortcuts.com/2015/

**Comment by madskristensen** [comment]
Fixed

**Comment by jchannon** [comment]
Website still shows it

**Comment by madskristensen** [comment]
I don't see it. Did you clear your cache or hit CTRL+F5?

**Comment by jchannon** [comment]
Yup but seems ok on iOS. Probably my laptop being dumb :)
